# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28896803b9a18825a95a5e4acd7e0584523eba02d756779eff1164a35a93e903b1a1b32204947e002e7948f769c9f097e467a6bff5eb1e987933c596c82c5c14

test:
  secret_key_base: 86399498cacff8281f1357440da882286b0368662594257f9c03cb3a38cf51343a7b320fe9ddc534748e3b45d58a26892d44dcf577b3d061baf32fbda286e02e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
